version: '3.8'

services:
  customrp-web:
    build: .
    container_name: customrp-web-24-7
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3000
      - NODE_ENV=production
